# Makefile.in generated by automake 1.9.2 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




SOURCES = $(libserver_SOURCES) $(libserver_debug_SOURCES) sizes.c $(testapp_SOURCES) $(timedrun_SOURCES)

srcdir = .
top_srcdir = .

pkgdatadir = $(datadir)/libserver
pkglibdir = $(libdir)/libserver
pkgincludedir = $(includedir)/libserver
top_builddir = .
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
INSTALL = /usr/bin/install -c
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
target_triplet = i686-pc-linux-gnu
bin_PROGRAMS = libserver$(EXEEXT)
noinst_PROGRAMS = libserver-debug$(EXEEXT) sizes$(EXEEXT) \
	testapp$(EXEEXT) timedrun$(EXEEXT)
am__append_1 = cache.c
am__append_2 = cache.c
#am__append_3 = solaris_priv.c
#am__append_4 = sasl_defs.c
#am__append_5 = memcached_dtrace.h
#am__append_6 = memcached_dtrace.h
#am__append_7 = memcached_dtrace.o
#am__append_8 = memcached_dtrace.o
#am__append_9 = memcached_debug_dtrace.o
#am__append_10 = memcached_debug_dtrace.o
#am__append_11 = memcached_dtrace.o memcached_debug_dtrace.o
DIST_COMMON = README $(am__configure_deps) $(pkginclude_HEADERS) \
	$(srcdir)/Makefile.am $(srcdir)/Makefile.in \
	$(srcdir)/config.h.in $(top_srcdir)/configure AUTHORS COPYING \
	ChangeLog INSTALL NEWS compile config.guess config.sub depcomp \
	install-sh missing
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/version.m4 \
	$(top_srcdir)/m4/c99-backport.m4 $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno configure.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(pkgincludedir)"
binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
PROGRAMS = $(bin_PROGRAMS) $(noinst_PROGRAMS)
am__libserver_SOURCES_DIST = memcached.c memcached.h hash.c hash.h \
	slabs.c slabs.h items.c items.h assoc.c assoc.h thread.c \
	daemon.c stats.c stats.h util.c util.h trace.h cache.h \
	sasl_defs.h modules/mod.c modules/mod.h \
	confparser/confparser.c confparser/confparser.h \
	confparser/dictionary.c confparser/dictionary.h \
	confparser/iniparser.c confparser/iniparser.h \
	confparser/queue.h cache.c solaris_priv.c sasl_defs.c
am__objects_1 = libserver-cache.$(OBJEXT)
#am__objects_2 =  \
#	libserver-solaris_priv.$(OBJEXT)
#am__objects_3 = libserver-sasl_defs.$(OBJEXT)
am_libserver_OBJECTS = libserver-memcached.$(OBJEXT) \
	libserver-hash.$(OBJEXT) libserver-slabs.$(OBJEXT) \
	libserver-items.$(OBJEXT) libserver-assoc.$(OBJEXT) \
	libserver-thread.$(OBJEXT) libserver-daemon.$(OBJEXT) \
	libserver-stats.$(OBJEXT) libserver-util.$(OBJEXT) \
	libserver-mod.$(OBJEXT) libserver-confparser.$(OBJEXT) \
	libserver-dictionary.$(OBJEXT) libserver-iniparser.$(OBJEXT) \
	$(am__objects_1) $(am__objects_2) $(am__objects_3)
libserver_OBJECTS = $(am_libserver_OBJECTS)
#am__DEPENDENCIES_1 = memcached_dtrace.o
am__libserver_debug_SOURCES_DIST = memcached.c memcached.h hash.c \
	hash.h slabs.c slabs.h items.c items.h assoc.c assoc.h \
	thread.c daemon.c stats.c stats.h util.c util.h trace.h \
	cache.h sasl_defs.h modules/mod.c modules/mod.h \
	confparser/confparser.c confparser/confparser.h \
	confparser/dictionary.c confparser/dictionary.h \
	confparser/iniparser.c confparser/iniparser.h \
	confparser/queue.h cache.c solaris_priv.c sasl_defs.c
am__objects_4 = libserver_debug-cache.$(OBJEXT)
#am__objects_5 = libserver_debug-solaris_priv.$(OBJEXT)
#am__objects_6 = libserver_debug-sasl_defs.$(OBJEXT)
am__objects_7 = libserver_debug-memcached.$(OBJEXT) \
	libserver_debug-hash.$(OBJEXT) libserver_debug-slabs.$(OBJEXT) \
	libserver_debug-items.$(OBJEXT) \
	libserver_debug-assoc.$(OBJEXT) \
	libserver_debug-thread.$(OBJEXT) \
	libserver_debug-daemon.$(OBJEXT) \
	libserver_debug-stats.$(OBJEXT) libserver_debug-util.$(OBJEXT) \
	libserver_debug-mod.$(OBJEXT) \
	libserver_debug-confparser.$(OBJEXT) \
	libserver_debug-dictionary.$(OBJEXT) \
	libserver_debug-iniparser.$(OBJEXT) $(am__objects_4) \
	$(am__objects_5) $(am__objects_6)
am_libserver_debug_OBJECTS = $(am__objects_7)
libserver_debug_OBJECTS = $(am_libserver_debug_OBJECTS)
#am__DEPENDENCIES_2 =  \
#	memcached_debug_dtrace.o
sizes_SOURCES = sizes.c
sizes_OBJECTS = sizes.$(OBJEXT)
sizes_LDADD = $(LDADD)
am__testapp_SOURCES_DIST = testapp.c util.c util.h cache.c
am__objects_8 = cache.$(OBJEXT)
am_testapp_OBJECTS = testapp.$(OBJEXT) util.$(OBJEXT) $(am__objects_8)
testapp_OBJECTS = $(am_testapp_OBJECTS)
testapp_LDADD = $(LDADD)
am_timedrun_OBJECTS = timedrun.$(OBJEXT)
timedrun_OBJECTS = $(am_timedrun_OBJECTS)
timedrun_LDADD = $(LDADD)
DEFAULT_INCLUDES = -I. -I$(srcdir) -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
SOURCES = $(libserver_SOURCES) $(libserver_debug_SOURCES) sizes.c \
	$(testapp_SOURCES) $(timedrun_SOURCES)
DIST_SOURCES = $(am__libserver_SOURCES_DIST) \
	$(am__libserver_debug_SOURCES_DIST) sizes.c \
	$(am__testapp_SOURCES_DIST) $(timedrun_SOURCES)
RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
	html-recursive info-recursive install-data-recursive \
	install-exec-recursive install-info-recursive \
	install-recursive installcheck-recursive installdirs-recursive \
	pdf-recursive ps-recursive uninstall-info-recursive \
	uninstall-recursive
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = `echo $$p | sed -e 's|^.*/||'`;
pkgincludeHEADERS_INSTALL = $(INSTALL_HEADER)
HEADERS = $(pkginclude_HEADERS)
ETAGS = etags
CTAGS = ctags
DIST_SUBDIRS = $(SUBDIRS)
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/songjian/code/libserver-2.0/missing --run aclocal-1.9
AMDEP_FALSE = #
AMDEP_TRUE = 
AMTAR = ${SHELL} /home/songjian/code/libserver-2.0/missing --run tar
AUTOCONF = ${SHELL} /home/songjian/code/libserver-2.0/missing --run autoconf
AUTOHEADER = ${SHELL} /home/songjian/code/libserver-2.0/missing --run autoheader
AUTOMAKE = ${SHELL} /home/songjian/code/libserver-2.0/missing --run automake-1.9
AWK = gawk
BUILD_CACHE_FALSE = #
BUILD_CACHE_TRUE = 
BUILD_DTRACE_FALSE = 
BUILD_DTRACE_TRUE = #
BUILD_SOLARIS_PRIVS_FALSE = 
BUILD_SOLARIS_PRIVS_TRUE = #
BUILD_SPECIFICATIONS_FALSE = 
BUILD_SPECIFICATIONS_TRUE = #
CC = gcc -std=gnu99
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2 -pthread -Wall -Werror -pedantic -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DTRACE = 
DTRACEFLAGS = 
DTRACE_INSTRUMENT_OBJ_FALSE = 
DTRACE_INSTRUMENT_OBJ_TRUE = #
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = grep -E
ENABLE_SASL = 
ENABLE_SASL_FALSE = 
ENABLE_SASL_TRUE = #
EXEEXT = 
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS =  -levent
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/songjian/code/libserver-2.0/missing --run makeinfo
OBJEXT = o
PACKAGE = libserver
PACKAGE_BUGREPORT = kyosold@gmail.com
PACKAGE_NAME = libserver
PACKAGE_STRING = libserver 1.5
PACKAGE_TARNAME = libserver
PACKAGE_VERSION = 1.5
PATH_SEPARATOR = :
PROFILER = /usr/bin/gcov
PROFILER_FLAGS = -fprofile-arcs -ftest-coverage
PROFILER_LDFLAGS = -lgcov
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 1.5
XML2RFC = no
XSLTPROC = /usr/bin/xsltproc
ac_ct_CC = gcc
ac_ct_STRIP = 
am__fastdepCC_FALSE = #
am__fastdepCC_TRUE = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = i686-pc-linux-gnu
build_alias = 
build_cpu = i686
build_os = linux-gnu
build_vendor = pc
datadir = ${prefix}/share
exec_prefix = ${prefix}
host = i686-pc-linux-gnu
host_alias = 
host_cpu = i686
host_os = linux-gnu
host_vendor = pc
includedir = ${prefix}/include
infodir = ${prefix}/info
install_sh = /home/songjian/code/libserver-2.0/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localstatedir = ${prefix}/var
mandir = ${prefix}/man
mkdir_p = mkdir -p --
oldincludedir = /usr/include
prefix = /usr/local
program_transform_name = s,x,x,
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
sysconfdir = ${prefix}/etc
target = i686-pc-linux-gnu
target_alias = 
target_cpu = i686
target_os = linux-gnu
target_vendor = pc
pkginclude_HEADERS = protocol_binary.h
BUILT_SOURCES = $(am__append_5)
testapp_SOURCES = testapp.c util.c util.h $(am__append_2)
timedrun_SOURCES = timedrun.c
libserver_SOURCES = memcached.c memcached.h hash.c hash.h slabs.c \
	slabs.h items.c items.h assoc.c assoc.h thread.c daemon.c \
	stats.c stats.h util.c util.h trace.h cache.h sasl_defs.h \
	modules/mod.c modules/mod.h confparser/confparser.c \
	confparser/confparser.h confparser/dictionary.c \
	confparser/dictionary.h confparser/iniparser.c \
	confparser/iniparser.h confparser/queue.h $(am__append_1) \
	$(am__append_3) $(am__append_4)
libserver_debug_SOURCES = $(libserver_SOURCES)
libserver_CPPFLAGS = -DNDEBUG
libserver_debug_LDADD = -lgcov $(am__append_9)
libserver_debug_CFLAGS = -fprofile-arcs -ftest-coverage
libserver_LDADD = $(am__append_7)
libserver_DEPENDENCIES = $(am__append_8)
libserver_debug_DEPENDENCIES = $(am__append_10)
CLEANFILES = $(am__append_6) $(am__append_11)
SUBDIRS = doc
DIST_DIRS = scripts
EXTRA_DIST = doc scripts t memcached.spec memcached_dtrace.d version.m4
MOSTLYCLEANFILES = *.gcov *.gcno *.gcda *.tcov
all: $(BUILT_SOURCES) config.h
	$(MAKE) $(AM_MAKEFLAGS) all-recursive

.SUFFIXES:
.SUFFIXES: .c .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu '; \
	      cd $(srcdir) && $(AUTOMAKE) --gnu  \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu  Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	cd $(top_srcdir) && $(AUTOHEADER)
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(mkdir_p) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	  ; then \
	    f=`echo "$$p1" | sed 's,^.*/,,;$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) '$$p' '$(DESTDIR)$(bindir)/$$f'"; \
	   $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) "$$p" "$(DESTDIR)$(bindir)/$$f" || exit 1; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo "$$p" | sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f '$(DESTDIR)$(bindir)/$$f'"; \
	  rm -f "$(DESTDIR)$(bindir)/$$f"; \
	done

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

clean-noinstPROGRAMS:
	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)
libserver$(EXEEXT): $(libserver_OBJECTS) $(libserver_DEPENDENCIES) 
	@rm -f libserver$(EXEEXT)
	$(LINK) $(libserver_LDFLAGS) $(libserver_OBJECTS) $(libserver_LDADD) $(LIBS)
libserver-debug$(EXEEXT): $(libserver_debug_OBJECTS) $(libserver_debug_DEPENDENCIES) 
	@rm -f libserver-debug$(EXEEXT)
	$(LINK) $(libserver_debug_LDFLAGS) $(libserver_debug_OBJECTS) $(libserver_debug_LDADD) $(LIBS)
sizes$(EXEEXT): $(sizes_OBJECTS) $(sizes_DEPENDENCIES) 
	@rm -f sizes$(EXEEXT)
	$(LINK) $(sizes_LDFLAGS) $(sizes_OBJECTS) $(sizes_LDADD) $(LIBS)
testapp$(EXEEXT): $(testapp_OBJECTS) $(testapp_DEPENDENCIES) 
	@rm -f testapp$(EXEEXT)
	$(LINK) $(testapp_LDFLAGS) $(testapp_OBJECTS) $(testapp_LDADD) $(LIBS)
timedrun$(EXEEXT): $(timedrun_OBJECTS) $(timedrun_DEPENDENCIES) 
	@rm -f timedrun$(EXEEXT)
	$(LINK) $(timedrun_LDFLAGS) $(timedrun_OBJECTS) $(timedrun_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/cache.Po
include ./$(DEPDIR)/libserver-assoc.Po
include ./$(DEPDIR)/libserver-cache.Po
include ./$(DEPDIR)/libserver-confparser.Po
include ./$(DEPDIR)/libserver-daemon.Po
include ./$(DEPDIR)/libserver-dictionary.Po
include ./$(DEPDIR)/libserver-hash.Po
include ./$(DEPDIR)/libserver-iniparser.Po
include ./$(DEPDIR)/libserver-items.Po
include ./$(DEPDIR)/libserver-memcached.Po
include ./$(DEPDIR)/libserver-mod.Po
include ./$(DEPDIR)/libserver-sasl_defs.Po
include ./$(DEPDIR)/libserver-slabs.Po
include ./$(DEPDIR)/libserver-solaris_priv.Po
include ./$(DEPDIR)/libserver-stats.Po
include ./$(DEPDIR)/libserver-thread.Po
include ./$(DEPDIR)/libserver-util.Po
include ./$(DEPDIR)/libserver_debug-assoc.Po
include ./$(DEPDIR)/libserver_debug-cache.Po
include ./$(DEPDIR)/libserver_debug-confparser.Po
include ./$(DEPDIR)/libserver_debug-daemon.Po
include ./$(DEPDIR)/libserver_debug-dictionary.Po
include ./$(DEPDIR)/libserver_debug-hash.Po
include ./$(DEPDIR)/libserver_debug-iniparser.Po
include ./$(DEPDIR)/libserver_debug-items.Po
include ./$(DEPDIR)/libserver_debug-memcached.Po
include ./$(DEPDIR)/libserver_debug-mod.Po
include ./$(DEPDIR)/libserver_debug-sasl_defs.Po
include ./$(DEPDIR)/libserver_debug-slabs.Po
include ./$(DEPDIR)/libserver_debug-solaris_priv.Po
include ./$(DEPDIR)/libserver_debug-stats.Po
include ./$(DEPDIR)/libserver_debug-thread.Po
include ./$(DEPDIR)/libserver_debug-util.Po
include ./$(DEPDIR)/sizes.Po
include ./$(DEPDIR)/testapp.Po
include ./$(DEPDIR)/timedrun.Po
include ./$(DEPDIR)/util.Po

.c.o:
	if $(COMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" -c -o $@ $<; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; fi
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	if $(COMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" -c -o $@ `$(CYGPATH_W) '$<'`; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; fi
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

libserver-memcached.o: memcached.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-memcached.o -MD -MP -MF "$(DEPDIR)/libserver-memcached.Tpo" -c -o libserver-memcached.o `test -f 'memcached.c' || echo '$(srcdir)/'`memcached.c; \
	then mv -f "$(DEPDIR)/libserver-memcached.Tpo" "$(DEPDIR)/libserver-memcached.Po"; else rm -f "$(DEPDIR)/libserver-memcached.Tpo"; exit 1; fi
#	source='memcached.c' object='libserver-memcached.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-memcached.o `test -f 'memcached.c' || echo '$(srcdir)/'`memcached.c

libserver-memcached.obj: memcached.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-memcached.obj -MD -MP -MF "$(DEPDIR)/libserver-memcached.Tpo" -c -o libserver-memcached.obj `if test -f 'memcached.c'; then $(CYGPATH_W) 'memcached.c'; else $(CYGPATH_W) '$(srcdir)/memcached.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver-memcached.Tpo" "$(DEPDIR)/libserver-memcached.Po"; else rm -f "$(DEPDIR)/libserver-memcached.Tpo"; exit 1; fi
#	source='memcached.c' object='libserver-memcached.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-memcached.obj `if test -f 'memcached.c'; then $(CYGPATH_W) 'memcached.c'; else $(CYGPATH_W) '$(srcdir)/memcached.c'; fi`

libserver-hash.o: hash.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-hash.o -MD -MP -MF "$(DEPDIR)/libserver-hash.Tpo" -c -o libserver-hash.o `test -f 'hash.c' || echo '$(srcdir)/'`hash.c; \
	then mv -f "$(DEPDIR)/libserver-hash.Tpo" "$(DEPDIR)/libserver-hash.Po"; else rm -f "$(DEPDIR)/libserver-hash.Tpo"; exit 1; fi
#	source='hash.c' object='libserver-hash.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-hash.o `test -f 'hash.c' || echo '$(srcdir)/'`hash.c

libserver-hash.obj: hash.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-hash.obj -MD -MP -MF "$(DEPDIR)/libserver-hash.Tpo" -c -o libserver-hash.obj `if test -f 'hash.c'; then $(CYGPATH_W) 'hash.c'; else $(CYGPATH_W) '$(srcdir)/hash.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver-hash.Tpo" "$(DEPDIR)/libserver-hash.Po"; else rm -f "$(DEPDIR)/libserver-hash.Tpo"; exit 1; fi
#	source='hash.c' object='libserver-hash.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-hash.obj `if test -f 'hash.c'; then $(CYGPATH_W) 'hash.c'; else $(CYGPATH_W) '$(srcdir)/hash.c'; fi`

libserver-slabs.o: slabs.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-slabs.o -MD -MP -MF "$(DEPDIR)/libserver-slabs.Tpo" -c -o libserver-slabs.o `test -f 'slabs.c' || echo '$(srcdir)/'`slabs.c; \
	then mv -f "$(DEPDIR)/libserver-slabs.Tpo" "$(DEPDIR)/libserver-slabs.Po"; else rm -f "$(DEPDIR)/libserver-slabs.Tpo"; exit 1; fi
#	source='slabs.c' object='libserver-slabs.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-slabs.o `test -f 'slabs.c' || echo '$(srcdir)/'`slabs.c

libserver-slabs.obj: slabs.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-slabs.obj -MD -MP -MF "$(DEPDIR)/libserver-slabs.Tpo" -c -o libserver-slabs.obj `if test -f 'slabs.c'; then $(CYGPATH_W) 'slabs.c'; else $(CYGPATH_W) '$(srcdir)/slabs.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver-slabs.Tpo" "$(DEPDIR)/libserver-slabs.Po"; else rm -f "$(DEPDIR)/libserver-slabs.Tpo"; exit 1; fi
#	source='slabs.c' object='libserver-slabs.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-slabs.obj `if test -f 'slabs.c'; then $(CYGPATH_W) 'slabs.c'; else $(CYGPATH_W) '$(srcdir)/slabs.c'; fi`

libserver-items.o: items.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-items.o -MD -MP -MF "$(DEPDIR)/libserver-items.Tpo" -c -o libserver-items.o `test -f 'items.c' || echo '$(srcdir)/'`items.c; \
	then mv -f "$(DEPDIR)/libserver-items.Tpo" "$(DEPDIR)/libserver-items.Po"; else rm -f "$(DEPDIR)/libserver-items.Tpo"; exit 1; fi
#	source='items.c' object='libserver-items.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-items.o `test -f 'items.c' || echo '$(srcdir)/'`items.c

libserver-items.obj: items.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-items.obj -MD -MP -MF "$(DEPDIR)/libserver-items.Tpo" -c -o libserver-items.obj `if test -f 'items.c'; then $(CYGPATH_W) 'items.c'; else $(CYGPATH_W) '$(srcdir)/items.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver-items.Tpo" "$(DEPDIR)/libserver-items.Po"; else rm -f "$(DEPDIR)/libserver-items.Tpo"; exit 1; fi
#	source='items.c' object='libserver-items.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-items.obj `if test -f 'items.c'; then $(CYGPATH_W) 'items.c'; else $(CYGPATH_W) '$(srcdir)/items.c'; fi`

libserver-assoc.o: assoc.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-assoc.o -MD -MP -MF "$(DEPDIR)/libserver-assoc.Tpo" -c -o libserver-assoc.o `test -f 'assoc.c' || echo '$(srcdir)/'`assoc.c; \
	then mv -f "$(DEPDIR)/libserver-assoc.Tpo" "$(DEPDIR)/libserver-assoc.Po"; else rm -f "$(DEPDIR)/libserver-assoc.Tpo"; exit 1; fi
#	source='assoc.c' object='libserver-assoc.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-assoc.o `test -f 'assoc.c' || echo '$(srcdir)/'`assoc.c

libserver-assoc.obj: assoc.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-assoc.obj -MD -MP -MF "$(DEPDIR)/libserver-assoc.Tpo" -c -o libserver-assoc.obj `if test -f 'assoc.c'; then $(CYGPATH_W) 'assoc.c'; else $(CYGPATH_W) '$(srcdir)/assoc.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver-assoc.Tpo" "$(DEPDIR)/libserver-assoc.Po"; else rm -f "$(DEPDIR)/libserver-assoc.Tpo"; exit 1; fi
#	source='assoc.c' object='libserver-assoc.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-assoc.obj `if test -f 'assoc.c'; then $(CYGPATH_W) 'assoc.c'; else $(CYGPATH_W) '$(srcdir)/assoc.c'; fi`

libserver-thread.o: thread.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-thread.o -MD -MP -MF "$(DEPDIR)/libserver-thread.Tpo" -c -o libserver-thread.o `test -f 'thread.c' || echo '$(srcdir)/'`thread.c; \
	then mv -f "$(DEPDIR)/libserver-thread.Tpo" "$(DEPDIR)/libserver-thread.Po"; else rm -f "$(DEPDIR)/libserver-thread.Tpo"; exit 1; fi
#	source='thread.c' object='libserver-thread.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-thread.o `test -f 'thread.c' || echo '$(srcdir)/'`thread.c

libserver-thread.obj: thread.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-thread.obj -MD -MP -MF "$(DEPDIR)/libserver-thread.Tpo" -c -o libserver-thread.obj `if test -f 'thread.c'; then $(CYGPATH_W) 'thread.c'; else $(CYGPATH_W) '$(srcdir)/thread.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver-thread.Tpo" "$(DEPDIR)/libserver-thread.Po"; else rm -f "$(DEPDIR)/libserver-thread.Tpo"; exit 1; fi
#	source='thread.c' object='libserver-thread.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-thread.obj `if test -f 'thread.c'; then $(CYGPATH_W) 'thread.c'; else $(CYGPATH_W) '$(srcdir)/thread.c'; fi`

libserver-daemon.o: daemon.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-daemon.o -MD -MP -MF "$(DEPDIR)/libserver-daemon.Tpo" -c -o libserver-daemon.o `test -f 'daemon.c' || echo '$(srcdir)/'`daemon.c; \
	then mv -f "$(DEPDIR)/libserver-daemon.Tpo" "$(DEPDIR)/libserver-daemon.Po"; else rm -f "$(DEPDIR)/libserver-daemon.Tpo"; exit 1; fi
#	source='daemon.c' object='libserver-daemon.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-daemon.o `test -f 'daemon.c' || echo '$(srcdir)/'`daemon.c

libserver-daemon.obj: daemon.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-daemon.obj -MD -MP -MF "$(DEPDIR)/libserver-daemon.Tpo" -c -o libserver-daemon.obj `if test -f 'daemon.c'; then $(CYGPATH_W) 'daemon.c'; else $(CYGPATH_W) '$(srcdir)/daemon.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver-daemon.Tpo" "$(DEPDIR)/libserver-daemon.Po"; else rm -f "$(DEPDIR)/libserver-daemon.Tpo"; exit 1; fi
#	source='daemon.c' object='libserver-daemon.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-daemon.obj `if test -f 'daemon.c'; then $(CYGPATH_W) 'daemon.c'; else $(CYGPATH_W) '$(srcdir)/daemon.c'; fi`

libserver-stats.o: stats.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-stats.o -MD -MP -MF "$(DEPDIR)/libserver-stats.Tpo" -c -o libserver-stats.o `test -f 'stats.c' || echo '$(srcdir)/'`stats.c; \
	then mv -f "$(DEPDIR)/libserver-stats.Tpo" "$(DEPDIR)/libserver-stats.Po"; else rm -f "$(DEPDIR)/libserver-stats.Tpo"; exit 1; fi
#	source='stats.c' object='libserver-stats.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-stats.o `test -f 'stats.c' || echo '$(srcdir)/'`stats.c

libserver-stats.obj: stats.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-stats.obj -MD -MP -MF "$(DEPDIR)/libserver-stats.Tpo" -c -o libserver-stats.obj `if test -f 'stats.c'; then $(CYGPATH_W) 'stats.c'; else $(CYGPATH_W) '$(srcdir)/stats.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver-stats.Tpo" "$(DEPDIR)/libserver-stats.Po"; else rm -f "$(DEPDIR)/libserver-stats.Tpo"; exit 1; fi
#	source='stats.c' object='libserver-stats.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-stats.obj `if test -f 'stats.c'; then $(CYGPATH_W) 'stats.c'; else $(CYGPATH_W) '$(srcdir)/stats.c'; fi`

libserver-util.o: util.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-util.o -MD -MP -MF "$(DEPDIR)/libserver-util.Tpo" -c -o libserver-util.o `test -f 'util.c' || echo '$(srcdir)/'`util.c; \
	then mv -f "$(DEPDIR)/libserver-util.Tpo" "$(DEPDIR)/libserver-util.Po"; else rm -f "$(DEPDIR)/libserver-util.Tpo"; exit 1; fi
#	source='util.c' object='libserver-util.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-util.o `test -f 'util.c' || echo '$(srcdir)/'`util.c

libserver-util.obj: util.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-util.obj -MD -MP -MF "$(DEPDIR)/libserver-util.Tpo" -c -o libserver-util.obj `if test -f 'util.c'; then $(CYGPATH_W) 'util.c'; else $(CYGPATH_W) '$(srcdir)/util.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver-util.Tpo" "$(DEPDIR)/libserver-util.Po"; else rm -f "$(DEPDIR)/libserver-util.Tpo"; exit 1; fi
#	source='util.c' object='libserver-util.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-util.obj `if test -f 'util.c'; then $(CYGPATH_W) 'util.c'; else $(CYGPATH_W) '$(srcdir)/util.c'; fi`

libserver-mod.o: modules/mod.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-mod.o -MD -MP -MF "$(DEPDIR)/libserver-mod.Tpo" -c -o libserver-mod.o `test -f 'modules/mod.c' || echo '$(srcdir)/'`modules/mod.c; \
	then mv -f "$(DEPDIR)/libserver-mod.Tpo" "$(DEPDIR)/libserver-mod.Po"; else rm -f "$(DEPDIR)/libserver-mod.Tpo"; exit 1; fi
#	source='modules/mod.c' object='libserver-mod.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-mod.o `test -f 'modules/mod.c' || echo '$(srcdir)/'`modules/mod.c

libserver-mod.obj: modules/mod.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-mod.obj -MD -MP -MF "$(DEPDIR)/libserver-mod.Tpo" -c -o libserver-mod.obj `if test -f 'modules/mod.c'; then $(CYGPATH_W) 'modules/mod.c'; else $(CYGPATH_W) '$(srcdir)/modules/mod.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver-mod.Tpo" "$(DEPDIR)/libserver-mod.Po"; else rm -f "$(DEPDIR)/libserver-mod.Tpo"; exit 1; fi
#	source='modules/mod.c' object='libserver-mod.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-mod.obj `if test -f 'modules/mod.c'; then $(CYGPATH_W) 'modules/mod.c'; else $(CYGPATH_W) '$(srcdir)/modules/mod.c'; fi`

libserver-confparser.o: confparser/confparser.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-confparser.o -MD -MP -MF "$(DEPDIR)/libserver-confparser.Tpo" -c -o libserver-confparser.o `test -f 'confparser/confparser.c' || echo '$(srcdir)/'`confparser/confparser.c; \
	then mv -f "$(DEPDIR)/libserver-confparser.Tpo" "$(DEPDIR)/libserver-confparser.Po"; else rm -f "$(DEPDIR)/libserver-confparser.Tpo"; exit 1; fi
#	source='confparser/confparser.c' object='libserver-confparser.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-confparser.o `test -f 'confparser/confparser.c' || echo '$(srcdir)/'`confparser/confparser.c

libserver-confparser.obj: confparser/confparser.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-confparser.obj -MD -MP -MF "$(DEPDIR)/libserver-confparser.Tpo" -c -o libserver-confparser.obj `if test -f 'confparser/confparser.c'; then $(CYGPATH_W) 'confparser/confparser.c'; else $(CYGPATH_W) '$(srcdir)/confparser/confparser.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver-confparser.Tpo" "$(DEPDIR)/libserver-confparser.Po"; else rm -f "$(DEPDIR)/libserver-confparser.Tpo"; exit 1; fi
#	source='confparser/confparser.c' object='libserver-confparser.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-confparser.obj `if test -f 'confparser/confparser.c'; then $(CYGPATH_W) 'confparser/confparser.c'; else $(CYGPATH_W) '$(srcdir)/confparser/confparser.c'; fi`

libserver-dictionary.o: confparser/dictionary.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-dictionary.o -MD -MP -MF "$(DEPDIR)/libserver-dictionary.Tpo" -c -o libserver-dictionary.o `test -f 'confparser/dictionary.c' || echo '$(srcdir)/'`confparser/dictionary.c; \
	then mv -f "$(DEPDIR)/libserver-dictionary.Tpo" "$(DEPDIR)/libserver-dictionary.Po"; else rm -f "$(DEPDIR)/libserver-dictionary.Tpo"; exit 1; fi
#	source='confparser/dictionary.c' object='libserver-dictionary.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-dictionary.o `test -f 'confparser/dictionary.c' || echo '$(srcdir)/'`confparser/dictionary.c

libserver-dictionary.obj: confparser/dictionary.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-dictionary.obj -MD -MP -MF "$(DEPDIR)/libserver-dictionary.Tpo" -c -o libserver-dictionary.obj `if test -f 'confparser/dictionary.c'; then $(CYGPATH_W) 'confparser/dictionary.c'; else $(CYGPATH_W) '$(srcdir)/confparser/dictionary.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver-dictionary.Tpo" "$(DEPDIR)/libserver-dictionary.Po"; else rm -f "$(DEPDIR)/libserver-dictionary.Tpo"; exit 1; fi
#	source='confparser/dictionary.c' object='libserver-dictionary.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-dictionary.obj `if test -f 'confparser/dictionary.c'; then $(CYGPATH_W) 'confparser/dictionary.c'; else $(CYGPATH_W) '$(srcdir)/confparser/dictionary.c'; fi`

libserver-iniparser.o: confparser/iniparser.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-iniparser.o -MD -MP -MF "$(DEPDIR)/libserver-iniparser.Tpo" -c -o libserver-iniparser.o `test -f 'confparser/iniparser.c' || echo '$(srcdir)/'`confparser/iniparser.c; \
	then mv -f "$(DEPDIR)/libserver-iniparser.Tpo" "$(DEPDIR)/libserver-iniparser.Po"; else rm -f "$(DEPDIR)/libserver-iniparser.Tpo"; exit 1; fi
#	source='confparser/iniparser.c' object='libserver-iniparser.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-iniparser.o `test -f 'confparser/iniparser.c' || echo '$(srcdir)/'`confparser/iniparser.c

libserver-iniparser.obj: confparser/iniparser.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-iniparser.obj -MD -MP -MF "$(DEPDIR)/libserver-iniparser.Tpo" -c -o libserver-iniparser.obj `if test -f 'confparser/iniparser.c'; then $(CYGPATH_W) 'confparser/iniparser.c'; else $(CYGPATH_W) '$(srcdir)/confparser/iniparser.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver-iniparser.Tpo" "$(DEPDIR)/libserver-iniparser.Po"; else rm -f "$(DEPDIR)/libserver-iniparser.Tpo"; exit 1; fi
#	source='confparser/iniparser.c' object='libserver-iniparser.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-iniparser.obj `if test -f 'confparser/iniparser.c'; then $(CYGPATH_W) 'confparser/iniparser.c'; else $(CYGPATH_W) '$(srcdir)/confparser/iniparser.c'; fi`

libserver-cache.o: cache.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-cache.o -MD -MP -MF "$(DEPDIR)/libserver-cache.Tpo" -c -o libserver-cache.o `test -f 'cache.c' || echo '$(srcdir)/'`cache.c; \
	then mv -f "$(DEPDIR)/libserver-cache.Tpo" "$(DEPDIR)/libserver-cache.Po"; else rm -f "$(DEPDIR)/libserver-cache.Tpo"; exit 1; fi
#	source='cache.c' object='libserver-cache.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-cache.o `test -f 'cache.c' || echo '$(srcdir)/'`cache.c

libserver-cache.obj: cache.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-cache.obj -MD -MP -MF "$(DEPDIR)/libserver-cache.Tpo" -c -o libserver-cache.obj `if test -f 'cache.c'; then $(CYGPATH_W) 'cache.c'; else $(CYGPATH_W) '$(srcdir)/cache.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver-cache.Tpo" "$(DEPDIR)/libserver-cache.Po"; else rm -f "$(DEPDIR)/libserver-cache.Tpo"; exit 1; fi
#	source='cache.c' object='libserver-cache.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-cache.obj `if test -f 'cache.c'; then $(CYGPATH_W) 'cache.c'; else $(CYGPATH_W) '$(srcdir)/cache.c'; fi`

libserver-solaris_priv.o: solaris_priv.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-solaris_priv.o -MD -MP -MF "$(DEPDIR)/libserver-solaris_priv.Tpo" -c -o libserver-solaris_priv.o `test -f 'solaris_priv.c' || echo '$(srcdir)/'`solaris_priv.c; \
	then mv -f "$(DEPDIR)/libserver-solaris_priv.Tpo" "$(DEPDIR)/libserver-solaris_priv.Po"; else rm -f "$(DEPDIR)/libserver-solaris_priv.Tpo"; exit 1; fi
#	source='solaris_priv.c' object='libserver-solaris_priv.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-solaris_priv.o `test -f 'solaris_priv.c' || echo '$(srcdir)/'`solaris_priv.c

libserver-solaris_priv.obj: solaris_priv.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-solaris_priv.obj -MD -MP -MF "$(DEPDIR)/libserver-solaris_priv.Tpo" -c -o libserver-solaris_priv.obj `if test -f 'solaris_priv.c'; then $(CYGPATH_W) 'solaris_priv.c'; else $(CYGPATH_W) '$(srcdir)/solaris_priv.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver-solaris_priv.Tpo" "$(DEPDIR)/libserver-solaris_priv.Po"; else rm -f "$(DEPDIR)/libserver-solaris_priv.Tpo"; exit 1; fi
#	source='solaris_priv.c' object='libserver-solaris_priv.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-solaris_priv.obj `if test -f 'solaris_priv.c'; then $(CYGPATH_W) 'solaris_priv.c'; else $(CYGPATH_W) '$(srcdir)/solaris_priv.c'; fi`

libserver-sasl_defs.o: sasl_defs.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-sasl_defs.o -MD -MP -MF "$(DEPDIR)/libserver-sasl_defs.Tpo" -c -o libserver-sasl_defs.o `test -f 'sasl_defs.c' || echo '$(srcdir)/'`sasl_defs.c; \
	then mv -f "$(DEPDIR)/libserver-sasl_defs.Tpo" "$(DEPDIR)/libserver-sasl_defs.Po"; else rm -f "$(DEPDIR)/libserver-sasl_defs.Tpo"; exit 1; fi
#	source='sasl_defs.c' object='libserver-sasl_defs.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-sasl_defs.o `test -f 'sasl_defs.c' || echo '$(srcdir)/'`sasl_defs.c

libserver-sasl_defs.obj: sasl_defs.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libserver-sasl_defs.obj -MD -MP -MF "$(DEPDIR)/libserver-sasl_defs.Tpo" -c -o libserver-sasl_defs.obj `if test -f 'sasl_defs.c'; then $(CYGPATH_W) 'sasl_defs.c'; else $(CYGPATH_W) '$(srcdir)/sasl_defs.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver-sasl_defs.Tpo" "$(DEPDIR)/libserver-sasl_defs.Po"; else rm -f "$(DEPDIR)/libserver-sasl_defs.Tpo"; exit 1; fi
#	source='sasl_defs.c' object='libserver-sasl_defs.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libserver_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libserver-sasl_defs.obj `if test -f 'sasl_defs.c'; then $(CYGPATH_W) 'sasl_defs.c'; else $(CYGPATH_W) '$(srcdir)/sasl_defs.c'; fi`

libserver_debug-memcached.o: memcached.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-memcached.o -MD -MP -MF "$(DEPDIR)/libserver_debug-memcached.Tpo" -c -o libserver_debug-memcached.o `test -f 'memcached.c' || echo '$(srcdir)/'`memcached.c; \
	then mv -f "$(DEPDIR)/libserver_debug-memcached.Tpo" "$(DEPDIR)/libserver_debug-memcached.Po"; else rm -f "$(DEPDIR)/libserver_debug-memcached.Tpo"; exit 1; fi
#	source='memcached.c' object='libserver_debug-memcached.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-memcached.o `test -f 'memcached.c' || echo '$(srcdir)/'`memcached.c

libserver_debug-memcached.obj: memcached.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-memcached.obj -MD -MP -MF "$(DEPDIR)/libserver_debug-memcached.Tpo" -c -o libserver_debug-memcached.obj `if test -f 'memcached.c'; then $(CYGPATH_W) 'memcached.c'; else $(CYGPATH_W) '$(srcdir)/memcached.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver_debug-memcached.Tpo" "$(DEPDIR)/libserver_debug-memcached.Po"; else rm -f "$(DEPDIR)/libserver_debug-memcached.Tpo"; exit 1; fi
#	source='memcached.c' object='libserver_debug-memcached.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-memcached.obj `if test -f 'memcached.c'; then $(CYGPATH_W) 'memcached.c'; else $(CYGPATH_W) '$(srcdir)/memcached.c'; fi`

libserver_debug-hash.o: hash.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-hash.o -MD -MP -MF "$(DEPDIR)/libserver_debug-hash.Tpo" -c -o libserver_debug-hash.o `test -f 'hash.c' || echo '$(srcdir)/'`hash.c; \
	then mv -f "$(DEPDIR)/libserver_debug-hash.Tpo" "$(DEPDIR)/libserver_debug-hash.Po"; else rm -f "$(DEPDIR)/libserver_debug-hash.Tpo"; exit 1; fi
#	source='hash.c' object='libserver_debug-hash.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-hash.o `test -f 'hash.c' || echo '$(srcdir)/'`hash.c

libserver_debug-hash.obj: hash.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-hash.obj -MD -MP -MF "$(DEPDIR)/libserver_debug-hash.Tpo" -c -o libserver_debug-hash.obj `if test -f 'hash.c'; then $(CYGPATH_W) 'hash.c'; else $(CYGPATH_W) '$(srcdir)/hash.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver_debug-hash.Tpo" "$(DEPDIR)/libserver_debug-hash.Po"; else rm -f "$(DEPDIR)/libserver_debug-hash.Tpo"; exit 1; fi
#	source='hash.c' object='libserver_debug-hash.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-hash.obj `if test -f 'hash.c'; then $(CYGPATH_W) 'hash.c'; else $(CYGPATH_W) '$(srcdir)/hash.c'; fi`

libserver_debug-slabs.o: slabs.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-slabs.o -MD -MP -MF "$(DEPDIR)/libserver_debug-slabs.Tpo" -c -o libserver_debug-slabs.o `test -f 'slabs.c' || echo '$(srcdir)/'`slabs.c; \
	then mv -f "$(DEPDIR)/libserver_debug-slabs.Tpo" "$(DEPDIR)/libserver_debug-slabs.Po"; else rm -f "$(DEPDIR)/libserver_debug-slabs.Tpo"; exit 1; fi
#	source='slabs.c' object='libserver_debug-slabs.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-slabs.o `test -f 'slabs.c' || echo '$(srcdir)/'`slabs.c

libserver_debug-slabs.obj: slabs.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-slabs.obj -MD -MP -MF "$(DEPDIR)/libserver_debug-slabs.Tpo" -c -o libserver_debug-slabs.obj `if test -f 'slabs.c'; then $(CYGPATH_W) 'slabs.c'; else $(CYGPATH_W) '$(srcdir)/slabs.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver_debug-slabs.Tpo" "$(DEPDIR)/libserver_debug-slabs.Po"; else rm -f "$(DEPDIR)/libserver_debug-slabs.Tpo"; exit 1; fi
#	source='slabs.c' object='libserver_debug-slabs.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-slabs.obj `if test -f 'slabs.c'; then $(CYGPATH_W) 'slabs.c'; else $(CYGPATH_W) '$(srcdir)/slabs.c'; fi`

libserver_debug-items.o: items.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-items.o -MD -MP -MF "$(DEPDIR)/libserver_debug-items.Tpo" -c -o libserver_debug-items.o `test -f 'items.c' || echo '$(srcdir)/'`items.c; \
	then mv -f "$(DEPDIR)/libserver_debug-items.Tpo" "$(DEPDIR)/libserver_debug-items.Po"; else rm -f "$(DEPDIR)/libserver_debug-items.Tpo"; exit 1; fi
#	source='items.c' object='libserver_debug-items.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-items.o `test -f 'items.c' || echo '$(srcdir)/'`items.c

libserver_debug-items.obj: items.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-items.obj -MD -MP -MF "$(DEPDIR)/libserver_debug-items.Tpo" -c -o libserver_debug-items.obj `if test -f 'items.c'; then $(CYGPATH_W) 'items.c'; else $(CYGPATH_W) '$(srcdir)/items.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver_debug-items.Tpo" "$(DEPDIR)/libserver_debug-items.Po"; else rm -f "$(DEPDIR)/libserver_debug-items.Tpo"; exit 1; fi
#	source='items.c' object='libserver_debug-items.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-items.obj `if test -f 'items.c'; then $(CYGPATH_W) 'items.c'; else $(CYGPATH_W) '$(srcdir)/items.c'; fi`

libserver_debug-assoc.o: assoc.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-assoc.o -MD -MP -MF "$(DEPDIR)/libserver_debug-assoc.Tpo" -c -o libserver_debug-assoc.o `test -f 'assoc.c' || echo '$(srcdir)/'`assoc.c; \
	then mv -f "$(DEPDIR)/libserver_debug-assoc.Tpo" "$(DEPDIR)/libserver_debug-assoc.Po"; else rm -f "$(DEPDIR)/libserver_debug-assoc.Tpo"; exit 1; fi
#	source='assoc.c' object='libserver_debug-assoc.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-assoc.o `test -f 'assoc.c' || echo '$(srcdir)/'`assoc.c

libserver_debug-assoc.obj: assoc.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-assoc.obj -MD -MP -MF "$(DEPDIR)/libserver_debug-assoc.Tpo" -c -o libserver_debug-assoc.obj `if test -f 'assoc.c'; then $(CYGPATH_W) 'assoc.c'; else $(CYGPATH_W) '$(srcdir)/assoc.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver_debug-assoc.Tpo" "$(DEPDIR)/libserver_debug-assoc.Po"; else rm -f "$(DEPDIR)/libserver_debug-assoc.Tpo"; exit 1; fi
#	source='assoc.c' object='libserver_debug-assoc.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-assoc.obj `if test -f 'assoc.c'; then $(CYGPATH_W) 'assoc.c'; else $(CYGPATH_W) '$(srcdir)/assoc.c'; fi`

libserver_debug-thread.o: thread.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-thread.o -MD -MP -MF "$(DEPDIR)/libserver_debug-thread.Tpo" -c -o libserver_debug-thread.o `test -f 'thread.c' || echo '$(srcdir)/'`thread.c; \
	then mv -f "$(DEPDIR)/libserver_debug-thread.Tpo" "$(DEPDIR)/libserver_debug-thread.Po"; else rm -f "$(DEPDIR)/libserver_debug-thread.Tpo"; exit 1; fi
#	source='thread.c' object='libserver_debug-thread.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-thread.o `test -f 'thread.c' || echo '$(srcdir)/'`thread.c

libserver_debug-thread.obj: thread.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-thread.obj -MD -MP -MF "$(DEPDIR)/libserver_debug-thread.Tpo" -c -o libserver_debug-thread.obj `if test -f 'thread.c'; then $(CYGPATH_W) 'thread.c'; else $(CYGPATH_W) '$(srcdir)/thread.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver_debug-thread.Tpo" "$(DEPDIR)/libserver_debug-thread.Po"; else rm -f "$(DEPDIR)/libserver_debug-thread.Tpo"; exit 1; fi
#	source='thread.c' object='libserver_debug-thread.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-thread.obj `if test -f 'thread.c'; then $(CYGPATH_W) 'thread.c'; else $(CYGPATH_W) '$(srcdir)/thread.c'; fi`

libserver_debug-daemon.o: daemon.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-daemon.o -MD -MP -MF "$(DEPDIR)/libserver_debug-daemon.Tpo" -c -o libserver_debug-daemon.o `test -f 'daemon.c' || echo '$(srcdir)/'`daemon.c; \
	then mv -f "$(DEPDIR)/libserver_debug-daemon.Tpo" "$(DEPDIR)/libserver_debug-daemon.Po"; else rm -f "$(DEPDIR)/libserver_debug-daemon.Tpo"; exit 1; fi
#	source='daemon.c' object='libserver_debug-daemon.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-daemon.o `test -f 'daemon.c' || echo '$(srcdir)/'`daemon.c

libserver_debug-daemon.obj: daemon.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-daemon.obj -MD -MP -MF "$(DEPDIR)/libserver_debug-daemon.Tpo" -c -o libserver_debug-daemon.obj `if test -f 'daemon.c'; then $(CYGPATH_W) 'daemon.c'; else $(CYGPATH_W) '$(srcdir)/daemon.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver_debug-daemon.Tpo" "$(DEPDIR)/libserver_debug-daemon.Po"; else rm -f "$(DEPDIR)/libserver_debug-daemon.Tpo"; exit 1; fi
#	source='daemon.c' object='libserver_debug-daemon.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-daemon.obj `if test -f 'daemon.c'; then $(CYGPATH_W) 'daemon.c'; else $(CYGPATH_W) '$(srcdir)/daemon.c'; fi`

libserver_debug-stats.o: stats.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-stats.o -MD -MP -MF "$(DEPDIR)/libserver_debug-stats.Tpo" -c -o libserver_debug-stats.o `test -f 'stats.c' || echo '$(srcdir)/'`stats.c; \
	then mv -f "$(DEPDIR)/libserver_debug-stats.Tpo" "$(DEPDIR)/libserver_debug-stats.Po"; else rm -f "$(DEPDIR)/libserver_debug-stats.Tpo"; exit 1; fi
#	source='stats.c' object='libserver_debug-stats.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-stats.o `test -f 'stats.c' || echo '$(srcdir)/'`stats.c

libserver_debug-stats.obj: stats.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-stats.obj -MD -MP -MF "$(DEPDIR)/libserver_debug-stats.Tpo" -c -o libserver_debug-stats.obj `if test -f 'stats.c'; then $(CYGPATH_W) 'stats.c'; else $(CYGPATH_W) '$(srcdir)/stats.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver_debug-stats.Tpo" "$(DEPDIR)/libserver_debug-stats.Po"; else rm -f "$(DEPDIR)/libserver_debug-stats.Tpo"; exit 1; fi
#	source='stats.c' object='libserver_debug-stats.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-stats.obj `if test -f 'stats.c'; then $(CYGPATH_W) 'stats.c'; else $(CYGPATH_W) '$(srcdir)/stats.c'; fi`

libserver_debug-util.o: util.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-util.o -MD -MP -MF "$(DEPDIR)/libserver_debug-util.Tpo" -c -o libserver_debug-util.o `test -f 'util.c' || echo '$(srcdir)/'`util.c; \
	then mv -f "$(DEPDIR)/libserver_debug-util.Tpo" "$(DEPDIR)/libserver_debug-util.Po"; else rm -f "$(DEPDIR)/libserver_debug-util.Tpo"; exit 1; fi
#	source='util.c' object='libserver_debug-util.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-util.o `test -f 'util.c' || echo '$(srcdir)/'`util.c

libserver_debug-util.obj: util.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-util.obj -MD -MP -MF "$(DEPDIR)/libserver_debug-util.Tpo" -c -o libserver_debug-util.obj `if test -f 'util.c'; then $(CYGPATH_W) 'util.c'; else $(CYGPATH_W) '$(srcdir)/util.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver_debug-util.Tpo" "$(DEPDIR)/libserver_debug-util.Po"; else rm -f "$(DEPDIR)/libserver_debug-util.Tpo"; exit 1; fi
#	source='util.c' object='libserver_debug-util.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-util.obj `if test -f 'util.c'; then $(CYGPATH_W) 'util.c'; else $(CYGPATH_W) '$(srcdir)/util.c'; fi`

libserver_debug-mod.o: modules/mod.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-mod.o -MD -MP -MF "$(DEPDIR)/libserver_debug-mod.Tpo" -c -o libserver_debug-mod.o `test -f 'modules/mod.c' || echo '$(srcdir)/'`modules/mod.c; \
	then mv -f "$(DEPDIR)/libserver_debug-mod.Tpo" "$(DEPDIR)/libserver_debug-mod.Po"; else rm -f "$(DEPDIR)/libserver_debug-mod.Tpo"; exit 1; fi
#	source='modules/mod.c' object='libserver_debug-mod.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-mod.o `test -f 'modules/mod.c' || echo '$(srcdir)/'`modules/mod.c

libserver_debug-mod.obj: modules/mod.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-mod.obj -MD -MP -MF "$(DEPDIR)/libserver_debug-mod.Tpo" -c -o libserver_debug-mod.obj `if test -f 'modules/mod.c'; then $(CYGPATH_W) 'modules/mod.c'; else $(CYGPATH_W) '$(srcdir)/modules/mod.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver_debug-mod.Tpo" "$(DEPDIR)/libserver_debug-mod.Po"; else rm -f "$(DEPDIR)/libserver_debug-mod.Tpo"; exit 1; fi
#	source='modules/mod.c' object='libserver_debug-mod.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-mod.obj `if test -f 'modules/mod.c'; then $(CYGPATH_W) 'modules/mod.c'; else $(CYGPATH_W) '$(srcdir)/modules/mod.c'; fi`

libserver_debug-confparser.o: confparser/confparser.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-confparser.o -MD -MP -MF "$(DEPDIR)/libserver_debug-confparser.Tpo" -c -o libserver_debug-confparser.o `test -f 'confparser/confparser.c' || echo '$(srcdir)/'`confparser/confparser.c; \
	then mv -f "$(DEPDIR)/libserver_debug-confparser.Tpo" "$(DEPDIR)/libserver_debug-confparser.Po"; else rm -f "$(DEPDIR)/libserver_debug-confparser.Tpo"; exit 1; fi
#	source='confparser/confparser.c' object='libserver_debug-confparser.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-confparser.o `test -f 'confparser/confparser.c' || echo '$(srcdir)/'`confparser/confparser.c

libserver_debug-confparser.obj: confparser/confparser.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-confparser.obj -MD -MP -MF "$(DEPDIR)/libserver_debug-confparser.Tpo" -c -o libserver_debug-confparser.obj `if test -f 'confparser/confparser.c'; then $(CYGPATH_W) 'confparser/confparser.c'; else $(CYGPATH_W) '$(srcdir)/confparser/confparser.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver_debug-confparser.Tpo" "$(DEPDIR)/libserver_debug-confparser.Po"; else rm -f "$(DEPDIR)/libserver_debug-confparser.Tpo"; exit 1; fi
#	source='confparser/confparser.c' object='libserver_debug-confparser.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-confparser.obj `if test -f 'confparser/confparser.c'; then $(CYGPATH_W) 'confparser/confparser.c'; else $(CYGPATH_W) '$(srcdir)/confparser/confparser.c'; fi`

libserver_debug-dictionary.o: confparser/dictionary.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-dictionary.o -MD -MP -MF "$(DEPDIR)/libserver_debug-dictionary.Tpo" -c -o libserver_debug-dictionary.o `test -f 'confparser/dictionary.c' || echo '$(srcdir)/'`confparser/dictionary.c; \
	then mv -f "$(DEPDIR)/libserver_debug-dictionary.Tpo" "$(DEPDIR)/libserver_debug-dictionary.Po"; else rm -f "$(DEPDIR)/libserver_debug-dictionary.Tpo"; exit 1; fi
#	source='confparser/dictionary.c' object='libserver_debug-dictionary.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-dictionary.o `test -f 'confparser/dictionary.c' || echo '$(srcdir)/'`confparser/dictionary.c

libserver_debug-dictionary.obj: confparser/dictionary.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-dictionary.obj -MD -MP -MF "$(DEPDIR)/libserver_debug-dictionary.Tpo" -c -o libserver_debug-dictionary.obj `if test -f 'confparser/dictionary.c'; then $(CYGPATH_W) 'confparser/dictionary.c'; else $(CYGPATH_W) '$(srcdir)/confparser/dictionary.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver_debug-dictionary.Tpo" "$(DEPDIR)/libserver_debug-dictionary.Po"; else rm -f "$(DEPDIR)/libserver_debug-dictionary.Tpo"; exit 1; fi
#	source='confparser/dictionary.c' object='libserver_debug-dictionary.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-dictionary.obj `if test -f 'confparser/dictionary.c'; then $(CYGPATH_W) 'confparser/dictionary.c'; else $(CYGPATH_W) '$(srcdir)/confparser/dictionary.c'; fi`

libserver_debug-iniparser.o: confparser/iniparser.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-iniparser.o -MD -MP -MF "$(DEPDIR)/libserver_debug-iniparser.Tpo" -c -o libserver_debug-iniparser.o `test -f 'confparser/iniparser.c' || echo '$(srcdir)/'`confparser/iniparser.c; \
	then mv -f "$(DEPDIR)/libserver_debug-iniparser.Tpo" "$(DEPDIR)/libserver_debug-iniparser.Po"; else rm -f "$(DEPDIR)/libserver_debug-iniparser.Tpo"; exit 1; fi
#	source='confparser/iniparser.c' object='libserver_debug-iniparser.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-iniparser.o `test -f 'confparser/iniparser.c' || echo '$(srcdir)/'`confparser/iniparser.c

libserver_debug-iniparser.obj: confparser/iniparser.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-iniparser.obj -MD -MP -MF "$(DEPDIR)/libserver_debug-iniparser.Tpo" -c -o libserver_debug-iniparser.obj `if test -f 'confparser/iniparser.c'; then $(CYGPATH_W) 'confparser/iniparser.c'; else $(CYGPATH_W) '$(srcdir)/confparser/iniparser.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver_debug-iniparser.Tpo" "$(DEPDIR)/libserver_debug-iniparser.Po"; else rm -f "$(DEPDIR)/libserver_debug-iniparser.Tpo"; exit 1; fi
#	source='confparser/iniparser.c' object='libserver_debug-iniparser.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-iniparser.obj `if test -f 'confparser/iniparser.c'; then $(CYGPATH_W) 'confparser/iniparser.c'; else $(CYGPATH_W) '$(srcdir)/confparser/iniparser.c'; fi`

libserver_debug-cache.o: cache.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-cache.o -MD -MP -MF "$(DEPDIR)/libserver_debug-cache.Tpo" -c -o libserver_debug-cache.o `test -f 'cache.c' || echo '$(srcdir)/'`cache.c; \
	then mv -f "$(DEPDIR)/libserver_debug-cache.Tpo" "$(DEPDIR)/libserver_debug-cache.Po"; else rm -f "$(DEPDIR)/libserver_debug-cache.Tpo"; exit 1; fi
#	source='cache.c' object='libserver_debug-cache.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-cache.o `test -f 'cache.c' || echo '$(srcdir)/'`cache.c

libserver_debug-cache.obj: cache.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-cache.obj -MD -MP -MF "$(DEPDIR)/libserver_debug-cache.Tpo" -c -o libserver_debug-cache.obj `if test -f 'cache.c'; then $(CYGPATH_W) 'cache.c'; else $(CYGPATH_W) '$(srcdir)/cache.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver_debug-cache.Tpo" "$(DEPDIR)/libserver_debug-cache.Po"; else rm -f "$(DEPDIR)/libserver_debug-cache.Tpo"; exit 1; fi
#	source='cache.c' object='libserver_debug-cache.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-cache.obj `if test -f 'cache.c'; then $(CYGPATH_W) 'cache.c'; else $(CYGPATH_W) '$(srcdir)/cache.c'; fi`

libserver_debug-solaris_priv.o: solaris_priv.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-solaris_priv.o -MD -MP -MF "$(DEPDIR)/libserver_debug-solaris_priv.Tpo" -c -o libserver_debug-solaris_priv.o `test -f 'solaris_priv.c' || echo '$(srcdir)/'`solaris_priv.c; \
	then mv -f "$(DEPDIR)/libserver_debug-solaris_priv.Tpo" "$(DEPDIR)/libserver_debug-solaris_priv.Po"; else rm -f "$(DEPDIR)/libserver_debug-solaris_priv.Tpo"; exit 1; fi
#	source='solaris_priv.c' object='libserver_debug-solaris_priv.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-solaris_priv.o `test -f 'solaris_priv.c' || echo '$(srcdir)/'`solaris_priv.c

libserver_debug-solaris_priv.obj: solaris_priv.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-solaris_priv.obj -MD -MP -MF "$(DEPDIR)/libserver_debug-solaris_priv.Tpo" -c -o libserver_debug-solaris_priv.obj `if test -f 'solaris_priv.c'; then $(CYGPATH_W) 'solaris_priv.c'; else $(CYGPATH_W) '$(srcdir)/solaris_priv.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver_debug-solaris_priv.Tpo" "$(DEPDIR)/libserver_debug-solaris_priv.Po"; else rm -f "$(DEPDIR)/libserver_debug-solaris_priv.Tpo"; exit 1; fi
#	source='solaris_priv.c' object='libserver_debug-solaris_priv.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-solaris_priv.obj `if test -f 'solaris_priv.c'; then $(CYGPATH_W) 'solaris_priv.c'; else $(CYGPATH_W) '$(srcdir)/solaris_priv.c'; fi`

libserver_debug-sasl_defs.o: sasl_defs.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-sasl_defs.o -MD -MP -MF "$(DEPDIR)/libserver_debug-sasl_defs.Tpo" -c -o libserver_debug-sasl_defs.o `test -f 'sasl_defs.c' || echo '$(srcdir)/'`sasl_defs.c; \
	then mv -f "$(DEPDIR)/libserver_debug-sasl_defs.Tpo" "$(DEPDIR)/libserver_debug-sasl_defs.Po"; else rm -f "$(DEPDIR)/libserver_debug-sasl_defs.Tpo"; exit 1; fi
#	source='sasl_defs.c' object='libserver_debug-sasl_defs.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-sasl_defs.o `test -f 'sasl_defs.c' || echo '$(srcdir)/'`sasl_defs.c

libserver_debug-sasl_defs.obj: sasl_defs.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -MT libserver_debug-sasl_defs.obj -MD -MP -MF "$(DEPDIR)/libserver_debug-sasl_defs.Tpo" -c -o libserver_debug-sasl_defs.obj `if test -f 'sasl_defs.c'; then $(CYGPATH_W) 'sasl_defs.c'; else $(CYGPATH_W) '$(srcdir)/sasl_defs.c'; fi`; \
	then mv -f "$(DEPDIR)/libserver_debug-sasl_defs.Tpo" "$(DEPDIR)/libserver_debug-sasl_defs.Po"; else rm -f "$(DEPDIR)/libserver_debug-sasl_defs.Tpo"; exit 1; fi
#	source='sasl_defs.c' object='libserver_debug-sasl_defs.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libserver_debug_CFLAGS) $(CFLAGS) -c -o libserver_debug-sasl_defs.obj `if test -f 'sasl_defs.c'; then $(CYGPATH_W) 'sasl_defs.c'; else $(CYGPATH_W) '$(srcdir)/sasl_defs.c'; fi`
uninstall-info-am:
install-pkgincludeHEADERS: $(pkginclude_HEADERS)
	@$(NORMAL_INSTALL)
	test -z "$(pkgincludedir)" || $(mkdir_p) "$(DESTDIR)$(pkgincludedir)"
	@list='$(pkginclude_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f=$(am__strip_dir) \
	  echo " $(pkgincludeHEADERS_INSTALL) '$$d$$p' '$(DESTDIR)$(pkgincludedir)/$$f'"; \
	  $(pkgincludeHEADERS_INSTALL) "$$d$$p" "$(DESTDIR)$(pkgincludedir)/$$f"; \
	done

uninstall-pkgincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(pkginclude_HEADERS)'; for p in $$list; do \
	  f=$(am__strip_dir) \
	  echo " rm -f '$(DESTDIR)$(pkgincludedir)/$$f'"; \
	  rm -f "$(DESTDIR)$(pkgincludedir)/$$f"; \
	done

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.
$(RECURSIVE_TARGETS):
	@set fnord $$MAKEFLAGS; amf=$$2; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	   || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

mostlyclean-recursive clean-recursive distclean-recursive \
maintainer-clean-recursive:
	@set fnord $$MAKEFLAGS; amf=$$2; \
	dot_seen=no; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	rev=''; for subdir in $$list; do \
	  if test "$$subdir" = "."; then :; else \
	    rev="$$subdir $$rev"; \
	  fi; \
	done; \
	rev="$$rev ."; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	   || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done
ctags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS: tags-recursive $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      tags="$$tags $$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS: ctags-recursive $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	mkdir $(distdir)
	$(mkdir_p) $(distdir)/m4
	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's|.|.|g'`; \
	list='$(DISTFILES)'; for file in $$list; do \
	  case $$file in \
	    $(srcdir)/*) file=`echo "$$file" | sed "s|^$$srcdirstrip/||"`;; \
	    $(top_srcdir)/*) file=`echo "$$file" | sed "s|^$$topsrcdirstrip/|$(top_builddir)/|"`;; \
	  esac; \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    dir="/$$dir"; \
	    $(mkdir_p) "$(distdir)$$dir"; \
	  else \
	    dir=''; \
	  fi; \
	  if test -d $$d/$$file; then \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test -d "$(distdir)/$$subdir" \
	    || $(mkdir_p) "$(distdir)/$$subdir" \
	    || exit 1; \
	    distdir=`$(am__cd) $(distdir) && pwd`; \
	    top_distdir=`$(am__cd) $(top_distdir) && pwd`; \
	    (cd $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$top_distdir" \
	        distdir="$$distdir/$$subdir" \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	$(MAKE) $(AM_MAKEFLAGS) \
	  top_distdir="$(top_distdir)" distdir="$(distdir)" \
	  dist-hook
	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(SHELL) $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bunzip2 -c $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && cd $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e '1{h;s/./=/g;p;x;}' -e '$${p;x;}'
distuninstallcheck:
	@cd $(distuninstallcheck_dir) \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) check-recursive
all-am: Makefile $(PROGRAMS) $(HEADERS) config.h
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(pkgincludedir)"; do \
	  test -z "$$dir" || $(mkdir_p) "$$dir"; \
	done
install: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:
	-test -z "$(MOSTLYCLEANFILES)" || rm -f $(MOSTLYCLEANFILES)

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
clean: clean-recursive

clean-am: clean-binPROGRAMS clean-generic clean-noinstPROGRAMS \
	mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

info: info-recursive

info-am:

install-data-am: install-pkgincludeHEADERS

install-exec-am: install-binPROGRAMS

install-info: install-info-recursive

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-info-am \
	uninstall-pkgincludeHEADERS

uninstall-info: uninstall-info-recursive

.PHONY: $(RECURSIVE_TARGETS) CTAGS GTAGS all all-am am--refresh check \
	check-am clean clean-binPROGRAMS clean-generic \
	clean-noinstPROGRAMS clean-recursive ctags ctags-recursive \
	dist dist-all dist-bzip2 dist-gzip dist-hook dist-shar \
	dist-tarZ dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-recursive \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am install-exec \
	install-exec-am install-info install-info-am install-man \
	install-pkgincludeHEADERS install-strip installcheck \
	installcheck-am installdirs installdirs-am maintainer-clean \
	maintainer-clean-generic maintainer-clean-recursive \
	mostlyclean mostlyclean-compile mostlyclean-generic \
	mostlyclean-recursive pdf pdf-am ps ps-am tags tags-recursive \
	uninstall uninstall-am uninstall-binPROGRAMS uninstall-info-am \
	uninstall-pkgincludeHEADERS


libserver_dtrace.h: memcached_dtrace.d
	${DTRACE} -h -s memcached_dtrace.d
	sed -e 's,void \*,const void \*,g' memcached_dtrace.h | \
            sed -e 's,char \*,const char \*,g' | tr '\t' ' ' > mmc_dtrace.tmp
	mv mmc_dtrace.tmp memcached_dtrace.h

libserver_dtrace.o: $(libserver_OBJECTS)
	$(DTRACE) $(DTRACEFLAGS) -G -o memcached_dtrace.o -s ${srcdir}/memcached_dtrace.d $(libserver_OBJECTS)

libserver_debug_dtrace.o: $(libserver_debug_OBJECTS)
	$(DTRACE) $(DTRACEFLAGS) -G -o memcached_debug_dtrace.o -s ${srcdir}/memcached_dtrace.d $(libserver_debug_OBJECTS)

test:	memcached-debug sizes testapp
	$(srcdir)/sizes
	$(srcdir)/testapp
	prove $(srcdir)/t
	@if test `basename $(PROFILER)` = "gcov"; then \
	  for file in memcached_debug-*.gc??; do \
	    mv -f $$file `echo $$file | sed 's/memcached_debug-//'`; \
	  done && \
	  for file in *.gcda; do \
	    srcfile=`echo $$file | sed 's/.gcda/.c/'`; \
	    if test -n "`echo $(libserver_debug_SOURCES) | grep $$srcfile`"; then \
	      echo `$(PROFILER) $$srcfile` | sed 's/'$$srcfile':.*//'; \
	    fi \
	  done \
	elif test `basename $(PROFILER)` = "tcov"; then \
	  files=`grep SRCFILE memcached-debug.profile/tcovd | sed 's/SRCFILE://' | sort | uniq` && \
	  $(PROFILER) -x memcached-debug.profile $$files 2>&1; \
	  for file in *.tcov; do \
	    srcfile=`echo $$file | sed 's/.tcov//'`; \
	    if test -n "`echo $(libserver_debug_SOURCES) | grep $$srcfile`"; then \
	      echo $$srcfile : `grep 'Percent of the file executed' $$file`; \
	    fi \
	  done \
	else :; fi

docs:
	(cat Doxyfile ; echo "PROJECT_NUMBER=`cat version.num`") | doxygen -

dist-hook:
	rm -f $(distdir)/*/*~ $(distdir)/t/lib/*~ $(distdir)/*~
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
